data:
  max_seq: 10
  train_size: 0.8
  batch_size: 1
  num_seq: 10
model: 
  embedding_dim: 256
  hidden_dim: 128
  max_seq_length: 10
  use_attention: False
train:
  lr: 0.01
  train_size: 0.8
  epochs: 5
  batch_size: 1
  optimizer: 2
  decay_ratio: 5.0

