data:
  max_seq: 20
  train_size: 0.8
  batch_size: 1
  num_seq: 10
model: 
  embedding_dim: 256
  hidden_dim: 128
  max_seq_length: 20
  use_attention: False
train:
  lr: 0.001
  train_size: 0.8
  epochs: 30
  batch_size: 1
  optimizer: 2
  decay_ratio: 5.0

