data:
  max_seq: 30
  train_size: 0.8
  batch_size: 1
model: 
  embedding_dim: 128
  hidden_dim: 128
  use_attention: True
  num_layers: 1
  feature_size: 128
  
train:
  lr: 0.0000001
  train_size: 0.8
  epochs: 10
  optimizer: 2         # 1 = same optimizer, 2 = different optimizer (for encoder and decoder)
  decoder_decay_ratio: 5.0
  decay_ratio: 10
  num_seq_process: 1
  clip: 50