data_senti:
  max_seq: 10
  train_size: 0.8
  batch_size: 16
  num_output: 3
  voc_init: True

model_senti:
  embedding_dim: 512
  lstm_hidden_dim: 512
  hidden_dim: 256
  hidden_dim2: 128
  n_layers: 3
  drop_prob: 0.5
  regression: False
  
train_senti:
    epochs: 500
    learning_rate: 0.0001

data_ende:
  max_seq: 10
  train_size: 0.8
  batch_size: 64
  min_seq: 3

model_ende: 
  hidden_dim: 500
  use_attention: True
  encoder_num_layers: 2
  decoder_num_layers: 2
  dropout: 0.1
  feature_size: 128
  checkpoint_iter: 32000 # from which to restart 
  
train_ende:
  lr: 0.0001
  clip: 50
  teacher_forcing_ratio: 1.0
  decoder_learning_ratio: 5.0
  n_iteration: 10000
  train_batches_per_val: 80
  val_batches_per_epoch: 20
  save_every: 100